# Generated by Django 6.0.3 on 2026-06-20 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0005_add_is_reversed_to_jurnalentry'),
        ('produk', '0009_alter_produk_gambar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jurnalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sumber', 'manual'), _negated=True), fields=('sumber', 'sumber_id'), name='unique_jurnal_per_source'),
        ),
    ]
