# Generated by Django 6.0.3 on 2026-05-22 09:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Profil'),
        ),
    ]
